name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build image
      run: docker build -t jeesmon/nginx-reverse-proxy:0.0.1 .
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push image
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        docker push jeesmon/nginx-reverse-proxy:0.0.1
